File database
NZWhale/wishlist_backend pull request #1
Opened 2021-03-24 15:35 UTC by NZWhale

2021-03-24 17:13 UTC, zverev requested changes

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/createMagicLink.ts
> +const databasePath = './data/WishListDB.json'
Looks like tests are failing because they use the same db

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/createMagicLink.ts
> +const createMagicLink = async (email: string) => new Promise((resolve, reject) => {
Create tests for this function

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/magicLinkHandler.ts
> +        .catch(err => console.log(err))
Send error response

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/magicLinkHandler.ts
> +                sendMagicLink(req.body.email, data)
This is async operation, it should be handled. User should know if mail was or was not sent.

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/sendMagicLink.ts
> +function sendMagicLink(email: string, magicLink: any) {
return promise

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/sendMagicLink.ts
> +            user: "nodemailerwb@gmail.com",
this should be in config

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/sendMagicLink.ts
> +    transporter.sendMail(mailDetails, function (err: Error) {
This should be inside verify

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/sendMagicLink.ts
> +          console.log("Server is ready to take our messages");
Error should be thrown

2021-03-24 17:13 UTC, zverev commented on handlers/magicLinkHandler/sendMagicLink.ts
> +            console.log('Email sent successfully');
Error should be thrown

2021-03-24 17:13 UTC, zverev commented on handlers/statusHandler/statusHandler.ts
> +const statusHandler = (req: any, res: any) => {
ANY!!!11

2021-03-24 17:13 UTC, zverev commented on index.ts
> +initialiseDB()
DB class should lazy-initialise db

2021-03-24 17:13 UTC, zverev commented on index.ts
> +.then(data => console.log(data))
What if not?

2021-03-24 17:13 UTC, zverev commented on index.ts
>  const port = "3000"
Should be in config

2021-03-24 17:13 UTC, zverev commented on interfaces.ts
> +    user_id: string
let's use camelCase

2021-03-24 17:13 UTC, zverev commented on package.json
> +    "initDB": "ts-node handlers/magicLinkHandler/createMagicLink.ts"
delete it

2021-03-25 09:58 UTC, NZWhale commented on addresses.ts
> +export const smtpPassword = 'BLNytXgpj76Hx0cf'
You promised to explain how to work with sensitive data. So now, I will just delete and update them

2021-03-28 10:43 UTC, merged